[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mimic_dataset"
version = "0.1.4"
description = "Mimic patients analysis python project."

authors = [
    { name = "Ram" }
]

dependencies = [
    "PyYAML==6.0.2"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov"
]

[project.scripts]
run = "mimic_dataset.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
mimic_dataset = ["resources/configs/**/*"]