name: Build and Deploy WHL

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Build wheel
        run: |
          pip install build
          python -m build

      - name: Install Databricks CLI
        run: |
          pip install databricks
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Upload to Databricks Volume
        run: |
          databricks fs cp \
          dist/*.whl \
          /Volumes/mimic_catalog/dbx_volumes/dbx-volume-artifacts/mimic-artifact/ \
          --overwrite
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST}}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN}}